version: '3.0'
services:
  endpoint:
    container_name: vue_datapump_endpoint
    build:
      context: .
      dockerfile: docker/updates-endpoint/Dockerfile
    env_file: docker/updates-endpoint/.env
    ports:
      - '6060:8080'
    volumes:
      - ./:/var/www
  worker:
    container_name: vue_datapump_worker
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    env_file: docker/worker/.env
    volumes:
      - ./:/var/www